"""
Configuration settings for PLANORA Dashboard
"""

# AWS Color Palette
AWS_SQUID_INK = "#232F3E"
AWS_ORANGE = "#FF9900"
AWS_BLUE = "#146EB4"
AWS_LIGHT_BLUE = "#00A8E1"
AWS_DARK_BG = "#16191f"

# Default Autoscaling Settings
DEFAULT_SCALE_OUT_THRESHOLD = 150  # req/min
DEFAULT_SCALE_IN_THRESHOLD = 50    # req/min
DEFAULT_COOLDOWN_PERIOD = 3        # minutes
DEFAULT_SIMULATION_SPEED = 0.5     # seconds

# Simulation Settings
SIMULATION_STEPS = 200
INITIAL_REPLICAS = 5
MAX_REPLICAS = 20
MIN_REPLICAS = 1

# Cost Settings
COST_PER_REPLICA = 0.1
FIXED_REPLICAS = 10

# Chart Settings
CHART_HEIGHT_MAIN = 400
CHART_HEIGHT_GAUGE = 250
CHART_HEIGHT_ERROR = 300

# Anomaly Detection Thresholds
ANOMALY_SPIKE_MULTIPLIER = 1.5
ANOMALY_DROP_MULTIPLIER = 0.5
ANOMALY_DROP_THRESHOLD = 30
